### ISSUE TITLE
Archivo SQL

### ISSUE THREAD

**Issue by EderU99** [efraindrummer/Control-de-acceso-con-NFC#2]
Hola, estoy haciendo el archivo sql pero no me conecta ya que no veo como hiciste la conexion por la tabla Usuarios. 
Tendras el archivo sql? o como hiciste la conexion mediante la tabla Usuarios

**Comment by efraindrummer** [comment]
Hola, la base de datos SQL tiene configuración especiales, deja busco el archivo sql ya que es un archivo especial ya que fue echa y normalizada para aceptar hexadecimales de tarjeta RFID

**Comment by EderU99** [comment]
Gracias ayer eche a jalar la pagina y funciona todo correcto pero aun no llego a lo del registro con tarjetas RFID ya que aun no tengo el material ya que lo pienso comprar este fin de mes. la verdad el proyecto es muy interesante y se planea usar a fines estudiantiles.

**Comment by efraindrummer** [comment]
te aviso en estos días si encuentro el archivo SQL y te lo comparto con todo gusto, el sistema te va a correr perfecto en entorno linux bro es STACK es LAMP

**Comment by EderU99** [comment]
Muchas Gracias hermano estamos al pendiente del archivo sql, igual si tienes un dia tiempo me gustaria saber como hiciste para que se conecte la tarjeta arduino con la base de datos en phpmyadmin (en la base de datos de xampp) y se este actualizando como muestras en el video la verdad que es una pasada esta genial el proyecto.
